// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALSWVU8Z8CIxl_Ec7DZ4-gVccpYkEw_tU',
    appId: '1:282434419561:web:293fbceeaadaa81c041bf8',
    messagingSenderId: '282434419561',
    projectId: 'finalexam-51ffb',
    authDomain: 'finalexam-51ffb.firebaseapp.com',
    databaseURL: 'https://finalexam-51ffb-default-rtdb.firebaseio.com',
    storageBucket: 'finalexam-51ffb.appspot.com',
    measurementId: 'G-VK8M52XNJD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDv4R4Oh_G6CRXopuwQCxENUv7W7w2h5O0',
    appId: '1:282434419561:android:164ba799766ed9a1041bf8',
    messagingSenderId: '282434419561',
    projectId: 'finalexam-51ffb',
    databaseURL: 'https://finalexam-51ffb-default-rtdb.firebaseio.com',
    storageBucket: 'finalexam-51ffb.appspot.com',
  );
}
